### PR TITLE
Add timeline component

### LINKED ISSUE #1064: Add Timeline component
Add Timeline component to Octant
 - https://clarity.design/documentation/timeline

We'll want to be able to support actions in this view.

### PR DESCRIPTION
**Pull request by GuessWhoSamFoo**
**What this PR does / why we need it**:
Adds a timeline component with support for actions via button group

**Which issue(s) this PR fixes**
- Fixes #1064 

**Special notes for your reviewer**:
Helpful boilerplate for setting up a button + timeline:

```
	bg := component.NewButtonGroup()
	bg.AddButton(component.Button{
		Name:         "testing",
		Payload:      action.Payload{"hello": "world"},
		Confirmation: nil,
		Modal:        component.NewModal(component.Title(component.NewText("test"))),
	})
	steps := []component.TimelineStep{
		{
			State:       component.TimelineStepNotStarted,
			Header:      "Header test",
			Title:       "Title test",
			Description: "Title description",
		},
	}
	timeline := component.NewTimeline(steps, false)
	timeline.Add(component.TimelineStep{
		State:       component.TimelineStepCurrent,
		Header:      "current test",
		Title:       "current title",
		Description: "current description",
		ButtonGroup: bg,
	}, component.TimelineStep{
		State:       component.TimelineStepProcessing,
		Header:      "loading",
		Title:       "loading title",
		Description: "loading description",
	})
```

### CODE REVIEW

**Comment by wwitzel3** [comment]
We have suggested this before, wondering how you feel about starting with the components we are adding this release.

Add a useful example of using this component to the example plugin? It could be nice show using an action handler to retrigger a specific part of the timeline and having that change the plugin state so that the timeline update starts again...

I'm thinking we can use `Sleep` calls to simulate the waiting states and an action handler to retry a step.

On first render, the step fails, on retry, set a pass flag, and render the successful timeline.

**Review by wwitzel3 — APPROVED** [review]
LGTM

**Comment by mklanjsek** [comment]
Works well, looks good - nicely done Sam!

**Comment by GuessWhoSamFoo** [comment]
https://github.com/vmware-tanzu/octant-example-plugins just got an update and will continue to grow in examples moving forward.

**Pull request merged**
