### PR TITLE
allow 3rd party code to easily embed Octant

### LINKED ISSUE #204: Allow the dashboard to be embedded in another program
I started to check if it was possible to embed Octant inside another Go application but right now a large portion of the code sits inside the `internal/` folder which prevents it do be imported.

The goal would be to automatically start/stop Octant when starting something else. It would allow things like an embedded Octant inside a Grafana plugin for instance.

I think moving `internal/dash` to `pkg/dash` would be enough by looking at this: https://github.com/vmware/octant/blob/d52b4b0286f865a3d2ad7d3ffb8d6e8bc1eb48ea/internal/commands/dash.go#L68-L92

Would you be open to that change? I'm happy to drive that change and the testing related to it 🙂

### PR DESCRIPTION
**Pull request by wwitzel3**
closes #204 #324 
Signed-off-by: Wayne Witzel III <wayne@riotousliving.com>

### CODE REVIEW

**Comment by GuessWhoSamFoo** [comment]
@GarySmith Was this what you had in mind?

**Comment by wwitzel3** [comment]
@GarySmith @ledor473 does this enable what you all need?

**Comment by ledor473** [comment]
@wwitzel3 I think it does, I would have to check if it's importable now and if I can run it, but from a quick look at the changes it appears fine

**Review by GuessWhoSamFoo — APPROVED** [review]
Let's make this available for now and we can always revert before the next release if it is not useful

**Comment by ledor473** [comment]
@wwitzel3 @GuessWhoSamFoo sorry for the delay, while I don't have the time to fully test it, the import went well. I just have to make our logger match your interface and once that's done it should work.

**Pull request merged**
