### PR TITLE
fix js mime type for Windows

### LINKED ISSUE #355: Blank page in browser (0.8.0, Windows)
I've downloaded Octant 0.8.0 and it does only show a blank page in all my browsers (edge dev, chrome, firefox)

From the log it seems as if the Content-Type for JavaScript-files is wrong. Here's an excerpt:

Loading module from “http://127.0.0.1:7777/main-es2015.f3cf8b8bca1b3debed1e.js” was blocked because of a disallowed MIME type (“text/plain”).

I'm using Octant on Windows 10.

### PR DESCRIPTION
**Pull request by wwitzel3**
Fixes #355 
Signed-off-by: Wayne Witzel III <wayne@riotousliving.com>

### CODE REVIEW

**Review by GuessWhoSamFoo — APPROVED** [review]
Can't seem to reproduce this on my windows setup but lgtm

**Comment by wwitzel3** [comment]
I could not reproduce either, but if you look at #355 you'll see the reporter was able to build my patch and test that is fixed the issue for them.

**Comment by maehld** [comment]
I hope it is ok to leave a comment here? Regarding the reproducibility. I checked the golang's mime code and found the code which gets the correct mime type from the registry. The key says "text/plain" on my system. I don't know why but I certainly didn't insert the key myself :-)

Here's a screenshot:

image

Maybe one could open a report with the golang team? They could just ignore the registry for well known content types or is that a bad thing?

**Comment by wwitzel3** [comment]
This is really good info, thank you @maehld

**Pull request merged**
