### PR TITLE
Dark theme and theme switch implementation

### LINKED ISSUE #36: Dark theme
Enable a dark theme option.

### PR DESCRIPTION
**Pull request by nfarruggiagl**
* Added Clarity's CSS for Dark Theme.
* Theme switcher button added to the main header.
* Dark Theme styles added for custom non-Clarity components such as namespace dropdown, yaml view and resource viewer.

fixes #36 

Screen Shot 2019-10-10 at 17 23 05

### CODE REVIEW

**Comment by bryanl** [comment]
Filters don't have dark mode

Screen Shot 2019-10-11 at 3 09 59 PM

**Comment by bryanl** [comment]
Should the separator be this color?

Screen Shot 2019-10-11 at 3 10 46 PM

**Comment by bryanl** [comment]
The label pills are hard to read in dark mode

Screen Shot 2019-10-11 at 3 11 49 PM

**Comment by bryanl** [comment]
In the light version of the app, the `:visited` anchors are the same color as the unvisited anchors. Is this something we want to keep consistent?

Screen Shot 2019-10-11 at 3 14 18 PM

**Review by GuessWhoSamFoo — CHANGES_REQUESTED** [review]
Pagination dropdown numbers are no longer visible

darkmode

**Comment by nfarruggiagl** [comment]
> Filters don't have dark mode
> 
> Screen Shot 2019-10-11 at 3 09 59 PM

Fixed!

**Comment by nfarruggiagl** [comment]
> Should the separator be this color?
> 
> Screen Shot 2019-10-11 at 3 10 46 PM

Fixed!

**Comment by nfarruggiagl** [comment]
> The label pills are hard to read in dark mode
> 
> Screen Shot 2019-10-11 at 3 11 49 PM

Fixed!

**Comment by nfarruggiagl** [comment]
> In the light version of the app, the `:visited` anchors are the same color as the unvisited anchors. Is this something we want to keep consistent?
> 
> Screen Shot 2019-10-11 at 3 14 18 PM

visited and unvisited are different in both themes.
Screen Shot 2019-10-11 at 18 32 13
Screen Shot 2019-10-11 at 18 32 25

**Comment by nfarruggiagl** [comment]
> Pagination dropdown numbers are no longer visible
> 
> darkmode

I was unable to reproduce this but it may be related to a bug with Clarity itself, since no custom CSS was applied to Datagrids. All styles there comes from Clarity.

**Comment by bryanl** [comment]
> > In the light version of the app, the `:visited` anchors are the same color as the unvisited anchors. Is this something we want to keep consistent?
> > Screen Shot 2019-10-11 at 3 14 18 PM
> 
> visited and unvisited are different in both themes.

Screen Shot 2019-10-12 at 9 07 43 AM

**Review by GuessWhoSamFoo — APPROVED** [review]

**Review by wwitzel3 — APPROVED** [review]
There is still the drop down count issue, but as mentioned that is in clarity.

**Pull request merged**
