### PR TITLE
Use go:embed directive to serve static assets

### LINKED ISSUE #1750: Remove rice box from build tools
https://tip.golang.org/doc/go1.16#library-embed

Go 1.16 offers support for embedded files. This should simplify build steps and reduce friction for a development environment. As part of the dependency bump, we should:

- Clean rice-box.go (which is currently ignored by git)
- Update Github action workflows
- Remove reference from `tools.go`; update `go.mod`
- Re-bundle `dist/dash-frontend` currently handled in `web/web.go`

### PR DESCRIPTION
**Pull request by xtreme-vikram-yadav**
- Remove dependency on go.rice
- Resolves #1750

**What this PR does / why we need it**:

- This PR utilizes the new embed:directive. 
- It gets rid of the dependency on https://github.com/GeertJohan/go.rice.
- It simplifies CI steps by omitting unnecessary generate steps.

**Which issue(s) this PR fixes**
- Fixes #1750

### CODE REVIEW

**Comment by xtreme-vikram-yadav** [comment]
This PR modifies few files but removes a bunch as part of re-vendoring of dependencies.
I cleaned up the vendors directory by rerunning go mod vendor.

**Comment by xtreme-vikram-yadav** [comment]
CI is failing as it runs everything on go 1.15. I'm looking into updating the go version

**Comment by wwitzel3** [comment]
For the generated code check use:
    `go run build.go generate`

For the lint check use:
   ` go run build.go fmt`

**Comment by xtreme-vikram-yadav** [comment]
Hey @wwitzel3 , both of these checks and other jobs are failing due to missing 'dist/octant' embedded files error.
Introduction of embed directives has made the files inside 'dist/octant' a build dependency. As mentioned in the last couple of paragraphs of packages docs(https://tip.golang.org/pkg/embed/#hdr-Directives), embed directive expects the directory (dist/octant in our case) to be non-empty or it will fail to build and there doesn't seem any way to make this optional. Use of native directives is cool, but this dependency on external files makes it annoying to run anything not related to building the project binary which actually needs these files. We can't even run commands via `go run build.go` without having `dist/octant` populated with something. Based on what we have, we have an option to go ahead with the embed directive but update all scripts which run octant (including build.go, ci) to setup expected directory structure, or we can keep using what we have until embed directive supported optionally empty directories. In my opinion, having a hard dependency on the external directories provides a bad development experience with octant and we should just keep using rice box for now.

**Comment by wwitzel3** [comment]
Ahh, yes, I see what you are talking about now. I think we can work around this by leveraging Go build tags and inverting the control so that the embedded frontend handler is set as a side-effect of importing and building the web.go package.

It will look something like this.

```diff --git a/build.go b/build.go
index e216e145..69769e1a 100644
--- a/build.go
+++ b/build.go
@@ -261,7 +261,7 @@ func build() {
 	if runtime.GOOS == "windows" {
 		artifact = "octant.exe"
 	}
-	runCmd("go", nil, "build", "-mod=vendor", "-o", "build/"+artifact, GO_FLAGS, "-v", "./cmd/octant")
+	runCmd("go", nil, "build", "-tags", "embedded", "-mod=vendor", "-o", "build/"+artifact, GO_FLAGS, "-v", "./cmd/octant")
 }
 
 func buildElectron() {
@@ -364,19 +364,6 @@ func webBuildElectron() {
 	if err := cleanCmd.Run(); err != nil {
 		log.Fatalf("web-build-electron: create dist/octant/ : %s", err)
 	}
-
-	// This is a workaround as embed directive fails when
-	// the embedded directory is empty.
-	// Directive in question is located at:
-	// https://github.com/vmware-tanzu/octant/blob/master/web/web.go#L10
-	newFileCmd := newCmd("touch", nil, "dist/octant/empty.txt")
-	newFileCmd.Stdout = os.Stdout
-	newFileCmd.Stderr = os.Stderr
-	newFileCmd.Stdin = os.Stdin
-	newFileCmd.Dir = "./web"
-	if err := newFileCmd.Run(); err != nil {
-		log.Fatalf("web-build-electron: create dist/octant/empty.txt : %s", err)
-	}
 }
 
 func serve() {
diff --git a/pkg/dash/dash.go b/pkg/dash/dash.go
index 61d0dfc5..055b1876 100644
--- a/pkg/dash/dash.go
+++ b/pkg/dash/dash.go
@@ -48,7 +48,7 @@ import (
 	"github.com/vmware-tanzu/octant/pkg/plugin"
 	pluginAPI "github.com/vmware-tanzu/octant/pkg/plugin/api"
 	"github.com/vmware-tanzu/octant/pkg/store"
-	"github.com/vmware-tanzu/octant/web"
+	_ "github.com/vmware-tanzu/octant/web"
 )
 
 type Options struct {
@@ -602,7 +602,7 @@ func newDash(listener net.Listener, namespace, uiURL string, browserPath string,
 		namespace:       namespace,
 		uiURL:           uiURL,
 		browserPath:     browserPath,
-		defaultHandler:  web.Handler,
+		defaultHandler:  octant.GetFrontendHandler,
 		willOpenBrowser: true,
 		apiHandler:      apiHandler,
 		pluginService:   pluginHandler,
diff --git a/pkg/octant/options.go b/pkg/octant/options.go
index 60fe8d02..a2db0272 100644
--- a/pkg/octant/options.go
+++ b/pkg/octant/options.go
@@ -10,8 +10,6 @@ import (
 	"context"
 	"fmt"
 	"net/http"
-
-	"github.com/vmware-tanzu/octant/web"
 )
 
 // options is an internal set of options that can be used to configure Octant. These are
@@ -28,7 +26,7 @@ type options struct {
 // buildOptions builds an options struct from a list of functional options.
 func buildOptions(list ...Option) options {
 	opts := options{
-		frontendHandler: defaultFrontendHandler,
+		frontendHandler: func(_ context.Context) (http.Handler, error) { return GetFrontendHandler() },
 		backendHandler: func(ctx context.Context) (handler http.Handler, err error) {
 			return nil, fmt.Errorf("backend handler is not configured")
 		},
@@ -48,7 +46,7 @@ type Option func(o *options)
 func FrontendURL(proxyURL string) Option {
 	return func(o *options) {
 		if proxyURL == "" {
-			o.frontendHandler = defaultFrontendHandler
+			o.frontendHandler = func(_ context.Context) (http.Handler, error) { return GetFrontendHandler() }
 			return
 		}
 
@@ -70,10 +68,23 @@ func BackendHandler(fn func(ctx context.Context) (http.Handler, error)) Option {
 	}
 }
 
+var frontendHandlerFn func() (http.Handler, error)
+
+func SetFrontendHandler(handlerFn func() (http.Handler, error)) {
+	frontendHandlerFn = handlerFn
+}
+
+func GetFrontendHandler() (http.Handler, error) {
+	if frontendHandlerFn != nil {
+		return frontendHandlerFn()
+	}
+	return defaultFrontendHandler()
+}
+
 // defaultFrontendHandler is the default factory for creating a frontend handler.
 // TODO: this namespace should not know about the web namespace.
-func defaultFrontendHandler(ctx context.Context) (http.Handler, error) {
-	return web.Handler()
+func defaultFrontendHandler() (http.Handler, error) {
+	return http.NotFoundHandler(), nil
 }
 
 func noCacheRootMiddleware(next http.Handler) http.Handler {
diff --git a/web/doc.go b/web/doc.go
new file mode 100644
index 00000000..47b19aed
--- /dev/null
+++ b/web/doc.go
@@ -0,0 +1,11 @@
+package web
+
+/*
+Copyright (c) 2020 the Octant contributors. All Rights Reserved.
+SPDX-License-Identifier: Apache-2.0
+*/
+
+/*
+This package is used when embedding the Frontend assests directly in to the Octant binary.
+This requires compiling Octant with `-tags embedded`
+*/
diff --git a/web/web.go b/web/web.go
index 8357d771..2b2848ba 100644
--- a/web/web.go
+++ b/web/web.go
@@ -1,3 +1,5 @@
+// +build embedded
+
 package web
 
 import (
@@ -5,6 +7,8 @@ import (
 	"io/fs"
 	"mime"
 	"net/http"
+
+	"github.com/vmware-tanzu/octant/pkg/octant"
 )
 
 //go:embed dist/octant
@@ -25,3 +29,7 @@ func Handler() (http.Handler, error) {
 
 	return http.FileServer(http.FS(fsys)), nil
 }
+
+func init() {
+	octant.SetFrontendHandler(Handler)
+}```

**Comment by wwitzel3** [comment]
I'll look at what is going on with this Windows test.

**Comment by wwitzel3** [comment]
Never mind, @xtreme-vikram-yadav is going to stay on this PR, I had the wrong issue.

**Review by wwitzel3 — APPROVED** [review]

**Pull request merged**
