### PR TITLE
reduce content refresh delay to 1s

### PR DESCRIPTION
**Pull request by bryanl**
This change will reduce the lag in dashboard view for a (tiny) increase in CPU.

### CODE REVIEW

**Comment by GuessWhoSamFoo** [comment]
Can't reproduce it consistently, but there might be a case where switching namesapces via dropdown doesn't switch

**Comment by bryanl** [comment]
> Can't reproduce it consistently, but there might be a case where switching namesapces via dropdown doesn't switch

Is this why cypress is failing?

**Comment by GuessWhoSamFoo** [comment]
Adding below to https://github.com/vmware-tanzu/octant/blob/master/web/cypress/integration/app_spec.js#L31 should fix the breaking test

```
        cy
            .location('hash')
            .should('include', '/' + namespace)
```

**Review by GuessWhoSamFoo — APPROVED** [review]
Re-ran the test and it passed :poop:

**Pull request merged**
