### PR TITLE
Allow table sorting by multiple keys

### PR DESCRIPTION
**Pull request by GuessWhoSamFoo**
**What this PR does / why we need it**:
~~This PR adds sorting with multiple keys and sorts items with an error status by default in order to increase visibility of unhealthy cluster items.~~ This is a **breaking API change** as `table.Sort` is in `pkg`

Since datagrids are paginated, this results in a poor user experience if the status of an object changes while a user is looking at it. We will need to rethink if the goal should be filtering instead.

**Which issue(s) this PR fixes**
- ref #1565 

Signed-off-by: GuessWhoSamFoo <foos@vmware.com>

### CODE REVIEW

**Comment by GuessWhoSamFoo** [comment]
there was discussion about how this might look more maintainable if we separated out the reverse param into its own method and have a sort that only requires one or more keys

**Comment by GuessWhoSamFoo** [comment]
Added `table.Reverse()` and removed the boolean from sort

**Review by wwitzel3 — APPROVED** [review]

**Review by wwitzel3 — APPROVED** [review]
Please add a change log entry for this and lets document this in the storybook stories?

**Comment by GuessWhoSamFoo** [comment]
@alexbrand Sorry this took a while to get merged!

**Pull request merged**
