### PR TITLE
Create util package and add method to create Link components from k8s objects

### LINKED ISSUE #1444: In Go extensions API provide utility method to create the Link ref for the specified Kubernetes object
**Describe the problem/challenge you have**

In our Starboard plugin, which is implemented in Go, we are displaying custom resources that have owner references set. To create the UI Link components we'd have to reverse-engineer the logic to build such URL refs. For example, we'd like to link to a Deployment or ReplicaSet with the given name in the specified namespace.

plugin_go_link_builder

**Describe the solution you'd like**

Go API method to construct `Link` components for the specified `ObjectMeta` and/or `OwnerReference`. A similar method exists for JS/TS: https://github.com/vmware-tanzu/octant/blob/master/pkg/plugin/javascript/dashboard_ref_path.go

**Anything else you would like to add:**

N/A

**Environment:**

- Octant version (use `octant version`): 0.16.0
- Kubernetes version (use `kubectl version`): any
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): any

### PR DESCRIPTION
**Pull request by ftovaro**
Signed-off-by: ftovaro <f.tovar12@gmail.com>

**What this PR does / why we need it**:
Create a new public package called util
Create a method that receives a k8s object and returns a Link component to use in the frontend

**Which issue(s) this PR fixes**
- Fixes #1444 

**Special notes for your reviewer**:

**Release note**:
```
release-note
```

### CODE REVIEW

**Comment by lenriquez** [comment]
Could you pls add the changelog file? :)

**Comment by ftovaro** [comment]
> Could you pls add the changelog file? :)

Done!

**Comment by GuessWhoSamFoo** [comment]
Here is a way to do it with exposing module manager as a link generator: https://github.com/GuessWhoSamFoo/octant/commit/d2f4262014b7a4da7864ba7fef6f43c877afdc00

It lets a plugin author do something like:
```
resp, err := request.DashboardClient.CreateLink(request.Context(), key)
resp.Link // component.Link
```
If you're interested in finishing this, maybe add another parameter for the link text?

**Comment by GuessWhoSamFoo** [comment]
superseded by #2276

**Pull request closed without merging**
