### PR TITLE
Create workload viewer

### PR DESCRIPTION
**Pull request by bryanl**
Create a workload viewer that shows the status of workloads running in a cluster. This will be the new home page for Octant.

 Workload shows status for pods in a namespaced grouped by owner. If the cluster
 supports the pod metrics API, it will also include CPU and memory metrics
 for the group of pods.

dark
light
No metrics server

### CODE REVIEW

**Comment by wwitzel3** [comment]
I started to look at this today but couldn't give my full attention because I distracted with #135 stuff. I'll give it a full dedicated code review tomorrow. Sorry for the delay in getting to this.

**Comment by wwitzel3** [comment]
When I was testing this it worked great on GKE (1.13), but was not working on a KIND (1.15) cluster, using the exact same YAML. (example/resources/deployment.yaml)

**Comment by bryanl** [comment]
> When I was testing this it worked great on GKE (1.13), but was not working on a KIND (1.15) cluster, using the exact same YAML. (example/resources/deployment.yaml)

Do you have a screenshot?

**Comment by wwitzel3** [comment]
no-workload-kind

No errors in the web console (besides preventDefault) and no errors in the terminal.

**Review by wwitzel3 — APPROVED** [review]

**Comment by LWJ** [comment]
I think this is currently causing problems on Windows as the root path is created using filepath.Join() instead of path.Join() at the moment:

https://github.com/vmware-tanzu/octant/blob/master/internal/modules/workloads/module.go#L86

**Pull request merged**
