### PR TITLE
Updated layout for Log search and filter UI

### PR DESCRIPTION
**Pull request by mklanjsek**
Implemented new layout based on design from @rossfenrick.  Also updated colors for both light and dark theme.

### CODE REVIEW

**Comment by wwitzel3** [comment]
I'm gonna start looking at this now, can you rebase and clean up all the merges.

**Comment by rossfenrick** [comment]
@mklanjsek From a design/layout perspective, looks great! Only thing I see missing is the shortening up of the timestamp values

**Comment by mklanjsek** [comment]
> @mklanjsek From a design/layout perspective, looks great! Only thing I see missing is the shortening up of the timestamp values

Oops, forgot about that - will do it right now.

**Comment by mklanjsek** [comment]
@wwitzel3 I think this is good to go now.

**Pull request merged**
