### PR TITLE
Fixed problem with jsoniter sorting

### LINKED ISSUE #2133: Labels causing layout shift and performance degradation
When kubernetes resources containing multiple labels are present, labels are sometimes updated in Octant UI without any changes in underlining label data. It's most likely happening because internal ordering of labels changes, causing different labels to move to the start of the list. This is causing layout shifts and affecting both user experience and screen update performance. It appears to be happening periodically after every ~10 seconds.

Here is an example of layout shift happening around 2:30 in recording:
https://user-images.githubusercontent.com/34245594/110654112-13ea1300-817b-11eb-80c1-3fcadf7e12d2.mov

As illustrated in performance dump, there are two layout shifts happening in this scenario, first is 41.5ms and second one 121.7ms long:
Screen Shot 2021-03-10 at 8 21 19 AM

The [unnecessary layout shifts](https://web.dev/cls/?utm_source=devtools) are degrading user experience and we should try to eliminate them.

### PR DESCRIPTION
**Pull request by mklanjsek**
- Refactored the `jsoniter` initialization code inside a single entry point in global utility package,
- Modified the `jsoniter` configuration to use combination of `ConfigFastest ` and `SortMapKeys ` flags,
- Verified that addressed both label and resource viewer issue from #2133,
- Added unit test to make sure json marshaling is properly sorting fields, 

Signed-off-by: Milan Klanjsek <mklanjsek@pivotal.io>

Fixes #2133

### CODE REVIEW

**Review by wwitzel3 — CHANGES_REQUESTED** [review]
This is not how we want to do this.

If we want to centralize the configuration, that's fine, but this isn't the way.

**Comment by wwitzel3** [comment]
If we want to do this, define our own internal `json` package, like this.

```
diff --git a/internal/json/json.go b/internal/json/json.go
new file mode 100644
index 00000000..2c3c26ca
--- /dev/null
+++ b/internal/json/json.go
@@ -0,0 +1,15 @@
+package json
+
+import jsoniter "github.com/json-iterator/go"
+
+var jsonConfig = jsoniter.Config{
+       EscapeHTML:                    false,
+       MarshalFloatWith6Digits:       true,
+       ObjectFieldMustBeSimpleString: true,
+       SortMapKeys:                   true,
+}.Froze()
+
+var NewEncoder = jsonConfig.NewEncoder
+var Unmarshal = jsonConfig.Unmarshal
+var Marshal = jsonConfig.Marshal
+var MarshalIndent = jsonConfig.MarshalIndent
```

**Comment by mklanjsek** [comment]
Thanks Wayne. I generally try to avoid shadowing packages, but on the second look I think you are right, that's better way of doing it.

**Comment by mklanjsek** [comment]
@wwitzel3 PTAL

**Review by wwitzel3 — APPROVED** [review]
Perfect, thank you @mklanjsek

**Pull request merged**
