### PR TITLE
Migrate to node 16 and npm 7

### LINKED ISSUE #1925: npm ERR! cb() never called!
xref: https://github.com/vmware-tanzu/octant/runs/1807187681?check_suite_focus=true#step:4:6

Likely has something to do with invalidating the npm cache

### PR DESCRIPTION
**Pull request by GuessWhoSamFoo**
**What this PR does / why we need it**:
https://github.com/npm/cli/wiki/%22cb()-never-called%3F--I'm-having-the-same-problem!%22

Since all npm commands in github actions use ` npm ci`, the lockfile will still be expected to be generated via node < 16 but will use the newer version at runtime.

 - Separated electron asset building steps in `build.go`
 - Some dependencies had to be bumped due to new peer dependency requirements
 - Bumping to node 16 (which eventually will become LTS in October) implicitly moves to npm 7
 - `marked` had to be removed from resolutions. xref: https://github.com/compodoc/compodoc/issues/1033

**Which issue(s) this PR fixes**
- Fixes #1925

### CODE REVIEW

**Comment by GuessWhoSamFoo** [comment]
@mklanjsek Passing 5/5 in a row (technically 15 b/c of build matrix). Am I missing anything here?

**Review by wwitzel3 — APPROVED** [review]

**Comment by mklanjsek** [comment]
@GuessWhoSamFoo Storybook does not run locally for me, empty screen and errors in console:

Screen Shot 2021-06-01 at 12 13 00 PM

**Comment by GuessWhoSamFoo** [comment]
Not sure what `react-docgen` and `react-is` are for as https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#react-peer-dependencies only states that `react` and `react-dom` are required peer dependencies.

The above error requires `react` and `react-dom` to have matching versions.

Also expected to close #2524

**Comment by mklanjsek** [comment]
Storybook is running nicely now. I had some issues running tests, but these were resolved with help from @GuessWhoSamFoo 

As for  `react-docgen` and `react-is` - I think they were used to generate args table in storybook docs pane.  However it looks like that was broken since upgrade to latest format (at least it's broken on [reference.octant.dev](https://reference.octant.dev)):
```
<ArgsTable story = "story name" />
```

So in regards to node/npm upgrade, I think this ready to go, storybook docs issues could be addressed in different PR.

**Review by mklanjsek — APPROVED** [review]

**Pull request merged**
