### PR TITLE
Add support for windows shells and bash

### LINKED ISSUE #1533: Change default shell to bash
Hello, 

First of all, Thank you for such an amazing software. It works great. :-) 

When we login into a pod, the default shell is set to sh. Sh is very limited, because of which whenever I am logging into a pod, I am passing the command su -c bash. 
Can we change the default shell to bash or is there some way we can pass pod startup command, so I can change shell there. Kindly let me know. Thank you.

Regards,
Akshay Sulakhe

### PR DESCRIPTION
**Pull request by GuessWhoSamFoo**
**What this PR does / why we need it**:
Iterate through common shells to give terminal instances a better chance of running.

**Which issue(s) this PR fixes**
- Fixes #1533 

Signed-off-by: GuessWhoSamFoo <foos@vmware.com>

### CODE REVIEW

**Review by wwitzel3 — CHANGES_REQUESTED** [review]
I'd like to see this being able to explicitly set it when the shell is known. For example, in the case of an ephemeral debugging image, we know what shell will be available.

**Comment by wwitzel3** [comment]
I'm going to think about how and what about this we might want to be testing.

**Comment by GuessWhoSamFoo** [comment]
Current approach is to reduce the space in half by finding out if it is a windows container based on the presents of a runtimeClass, tolerations, or a nodeSelector in the pod spec (checking volume mounts for a path seems redundant).

There doesn't seem to be a standard way to tell the default shell in a container otherwise. In other words, octant still has to guess if a given linux container uses sh, bash, something else, or none of them.

**Comment by GuessWhoSamFoo** [comment]
Rebased and updated to check for windows labels before attempting any of the windows shells. Per https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/ , `Windows containers have to be scheduled on Windows nodes` so it is same to assume a pod schedule for a windows node must run a windows container.

**Review by wwitzel3 — APPROVED** [review]

**Comment by lloydchang** [comment]
To Whom It May Concern:

Consider upgrading to Octant [v0.19.0](https://github.com/vmware-tanzu/octant/releases/tag/v0.19.0) if you're using Octant [v0.17.0](https://github.com/vmware-tanzu/octant/releases/tag/v0.17.0) and [v0.18.0](https://github.com/vmware-tanzu/octant/releases/tag/v0.18.0).

**Why:** Feature [Change default shell to bash #1533](https://github.com/vmware-tanzu/octant/issues/1533)'s initial implementation, [Add support for windows shells and bash #1749](https://github.com/vmware-tanzu/octant/pull/1749) released in [v0.17.0](https://github.com/vmware-tanzu/octant/releases/tag/v0.17.0) and [v0.18.0](https://github.com/vmware-tanzu/octant/releases/tag/v0.18.0), has a bug of:
```
OCI runtime exec failed: ...
(process exited)
```
with operating systems without `bash`, e.g. Alpine Linux with `sh` only.

A bug fix [increase timeout for remote cmd stream setup #2258](https://github.com/vmware-tanzu/octant/pull/2258) released in [v0.19.0](https://github.com/vmware-tanzu/octant/releases/tag/v0.19.0), fixed a similar bug [No option to choose the interpreter on the terminal #2164](https://github.com/vmware-tanzu/octant/issues/2164).

After the bug fix, operating systems without `bash`, such as Alpine Linux, can start `sh` successfully

Thank you.

**Pull request merged**
