### PR TITLE
Fix hover on collapsed navigation

### PR DESCRIPTION
**Pull request by GuessWhoSamFoo**
Fixes:

hover

Signed-off-by: GuessWhoSamFoo <foos@vmware.com>

### CODE REVIEW

**Review by mklanjsek — CHANGES_REQUESTED** [review]
It looks good, except that it doesn't seem to work with the light theme.

**Comment by mklanjsek** [comment]
The light theme behavior could be related to #1084

**Comment by wwitzel3** [comment]
dismiss-flyout

Works well for me in both dark and light mode.

**Review by wwitzel3 — APPROVED** [review]

**Comment by mklanjsek** [comment]
The icon is not changing color on hover in light theme the same way it's doing in the dark theme. You can see that in the above recording from Wayne. It's probably just not the correct color applied in light theme.

**Comment by wwitzel3** [comment]
Yeah, that's covered by #1084 that's not a blocker for this.

image

**Review by mklanjsek — APPROVED** [review]
We can handle light theme color in separate PR

**Pull request merged**
