### PR TITLE
Labels/selectors will no longer overflow their containers

### LINKED ISSUE #770: Labels/selectors overflow their containers
**What steps did you take and what happened:**

Screen Shot 2020-03-12 at 11 14 06 AM

**What did you expect to happen:**

The labels should fit in their container. Probably should more aggressively use vertical space as well.

- Octant version (use `octant version`): 

Version:  (dev-version)
Git commit:  df6e6084
Built:  2020-03-12T15:13:10Z

- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Mac Chrome

### PR DESCRIPTION
**Pull request by nfarruggiagl**
Signed-off-by: Nicolas Farruggia <nfarruggia@vmware.com>

**What this PR does / why we need it**:
Labels/selectors will no longer overflow their containers

**Which issue(s) this PR fixes**
- Fixes #770 

**Special notes for your reviewer**:
Datagrids cells will decide the best disposition for the labels inside of it depending of available size

**Release note**:
```
release-note
```

### CODE REVIEW

**Comment by nfarruggiagl** [comment]
> This fixed the `Selector` column nicely, but the `Labels` column is now messed up (badge is overflowing), see here:
> image

Actually is not messed up, this is how Datagrid determined the best possible view for labels. It's using a column-direction because if it uses row-direction then will have the overflow issue again, I agree with you @mklanjsek , the label's position is odd, but is either that or overflowing the container :( .. maybe @rossfenrick has another idea ??

**Comment by mklanjsek** [comment]
That does not look right to me - the badge looks weird in the separate row.

**Comment by wwitzel3** [comment]
We want to add ellipsis and not overflow the container, we want to the row heights consistent.

**Comment by nfarruggiagl** [comment]
With the latest changes, Labels & Badges will no longer wrap, they will always be in the same row to make row's height consistent as expected. If the names are too long, they will have ellipsis:

Screen Shot 2020-04-13 at 10 42 30

Note: Sometimes (if we open a signpost in the last row for example), the Datagrid will create a vertical scroll, this is due to the way Clarity's Datagrid work. I tried to find a workaround to avoid this but it was impossible to do it without breaking other parts of the Datagrid. I think until it supports overflowing without breaking, this is the best we can do.

Screen Shot 2020-04-13 at 10 42 55

**Comment by mklanjsek** [comment]
Looking good with latest changes!

**Pull request merged**
