### PR TITLE
tag nightly

### PR DESCRIPTION
**Pull request by wwitzel3**
Signed-off-by: Wayne Witzel III <wayne@riotousliving.com>

**What this PR does / why we need it**:
Fixes the nightly build process that has been offline since April 4th when we disabled the drone nightly build.

### CODE REVIEW

**Comment by wwitzel3** [comment]
I'm testing this over on my fork tonight to see if setting the tag fixes the publishing issue.

**Comment by GuessWhoSamFoo** [comment]
how did this look on the fork?

**Comment by wwitzel3** [comment]
It can't parse the env variable again, will the call to push to the bucket is failing, so I need to jiggle the wires some more.

**Comment by wwitzel3** [comment]
Confirmed that this new approach works on my personal fork.

https://github.com/wwitzel3/octant/actions/runs/77555669

**Review by GuessWhoSamFoo — APPROVED** [review]

**Pull request merged**
