### PR TITLE
Show loading screen when content is not ready

### LINKED ISSUE #506: Show a better loading screen.
We should show a loading screen while we wait for content response length to be greater than 0.

https://github.com/vmware-tanzu/octant/blob/d48f76ced7939d837c1995f6b43acebf3d54bd47/web/src/app/modules/overview/overview.component.ts#L148

### PR DESCRIPTION
**Pull request by nfarruggiagl**
Signed-off-by: Nicolas Farruggia <nfarruggia@vmware.com>

**What this PR does / why we need it**:
Show a better loading screen
Loading

**Which issue(s) this PR fixes**
- Fixes #506 

**Special notes for your reviewer**:

**Release note**:
```
release-note
```

### CODE REVIEW

**Comment by GuessWhoSamFoo** [comment]
There is an existing loading component which is used for showing the spinner for a process happening on the backed. The changes here are for the time it takes to load all frontend components from a content response.

We also discussed during standup today about adding a delay before showing a the spinner. Maybe add a timer for 500ms? (this might require some tuning so that the spinner doesn't seem annoying)

**Review by mklanjsek — CHANGES_REQUESTED** [review]
Both Sam and I looked into this and played around with it.  In general it works great!  The only small issue is when response from backend returns very quickly, for example if you do not have any resources like in my case RBAC - in that case spinner shows so briefly resulting in noticeable flicker.  We recommend adding the initial delay before showing spinner (maybe 500-1000ms), so the spinner only shows up for longer queries and prevents the flicker.

**Comment by mklanjsek** [comment]
@GuessWhoSamFoo please update if I forgot something!

**Comment by mklanjsek** [comment]
OK, I'll finish that.

**Comment by mklanjsek** [comment]
Made following changes:
- Added logic so spinner does not show up if request takes < 650ms,
- In case spinner shows up, make sure it stays on for at least 1sec,
- Make spinner work when changing namespaces,

**Review by mklanjsek — APPROVED** [review]

**Review by wwitzel3 — APPROVED** [review]

**Pull request merged**
