### PR TITLE
Memory caching for CRD navigation entries

### PR DESCRIPTION
**Pull request by mklanjsek**
During performance testing, I noticed that we are rebuilding a list of CRD navigation entries twice per second, for cluster scope and current namespace. That is very costly operation taking ~500ms for larger CRD sets. To address the issue, I added a memory cache holding CRD navigation entries. Cache is invalidated every time new CRD appears or goes away.

Performance improvement is considerable but it depends on number of CRDs in cluster/namespace - I am seeing 15-20% improvement on larger sets on my mac.

Signed-off-by: Milan Klanjsek <mklanjsek@pivotal.io>

### CODE REVIEW

**Comment by wwitzel3** [comment]
Good start, this will need to be tied in to the Add/Update/Delete events of crd_watcher.go so that it removes old CRDS and adds new CRDs as they are applied. This will only cache the CRDs that are installed at the time you startup Octant.

**Comment by mklanjsek** [comment]
@wwitzel3 I already handle Add/Delete in `crd_watcher`, invalidating the cache there so it's recreated during next call.

**Comment by wwitzel3** [comment]
> @wwitzel3 I already handle Add/Delete in `crd_watcher`, invalidating the cache there so it's recreated during next call.

I see it now, probably was just GitHub not showing me the whole diff.

**Comment by wwitzel3** [comment]
Current:
image

This change alone:
image

This change combined with the #2102 branch
image

**Review by wwitzel3 — CHANGES_REQUESTED** [review]
This introduces a data race since many go routines can be calling `CRDEntries`, compiling with the `-race` flag reports a race with the sort.Slice in pkg/navigation/navigation.go 88-90

**Comment by mklanjsek** [comment]
Good catch Wayne, missed the race condition.  I eliminated the redundant sort on cached object and as a result the race condition is gone now.

Discouraged by negligible performance gain in your tests, makes me wonder if it's worth it...

**Comment by wwitzel3** [comment]
Negligible? Avg. 50% improvement once cached, that's a big improvement.

**Comment by mklanjsek** [comment]
Ooops my bad, didn't read that well 🤦  Definitely not negligible!

**Comment by wwitzel3** [comment]
I want to think about this a bit more, the idea is solid and effective. I'm not sure I like the current implementation of just slapping a global in to navigation and calling it from the watcher callbacks and accessing it in `CRDEntires` and `CustomResourceDefinitions`.

Also there will need to be at least a simple assertion test: non-cache call, cache call, clear cache, non-cache call, cache call.

**Comment by wwitzel3** [comment]
@mklanjsek and I talked about this, we will implement a cache layer and then overview and custom overview will maintain their own cache of the `CRDEntries` call. This is because the modules actually care about different results and the CRDEntires function is bi-modal depending of if you want namespace scoped CRDs or not.

**Comment by mklanjsek** [comment]
Waiting until #2144 is merged before finishing this.

**Comment by mklanjsek** [comment]
@wwitzel3 PTAL

**Comment by wwitzel3** [comment]
Please rebase, there is a failing test when merged with master because we no longer use `RegisterOnUpdate` methods.

**Comment by mklanjsek** [comment]
Rebased and fixed test failure.

**Review by wwitzel3 — APPROVED** [review]

**Pull request merged**
