### PR TITLE
Add link generator to DashboardClient

### LINKED ISSUE #1444: In Go extensions API provide utility method to create the Link ref for the specified Kubernetes object
**Describe the problem/challenge you have**

In our Starboard plugin, which is implemented in Go, we are displaying custom resources that have owner references set. To create the UI Link components we'd have to reverse-engineer the logic to build such URL refs. For example, we'd like to link to a Deployment or ReplicaSet with the given name in the specified namespace.

plugin_go_link_builder

**Describe the solution you'd like**

Go API method to construct `Link` components for the specified `ObjectMeta` and/or `OwnerReference`. A similar method exists for JS/TS: https://github.com/vmware-tanzu/octant/blob/master/pkg/plugin/javascript/dashboard_ref_path.go

**Anything else you would like to add:**

N/A

**Environment:**

- Octant version (use `octant version`): 0.16.0
- Kubernetes version (use `kubectl version`): any
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): any

### PR DESCRIPTION
**Pull request by GuessWhoSamFoo**
**What this PR does / why we need it**:

Usage: `request.DashboardClient.CreateLink(request.Context(), key)`

 - Returns a link response that has a link component with the object's name as the link text as default.

**Which issue(s) this PR fixes**
- Fixes #1444

### CODE REVIEW

**Review by wwitzel3 — APPROVED** [review]
Thank you for checking this one off the list.

**Comment by wwitzel3** [comment]
Can you create an issue to add this to an example plugin as well? I think showing the usage of this will be useful to plugin authors.

**Comment by GuessWhoSamFoo** [comment]
I'm inclined to say storybook should be for component rather than API documentation. We can add an example plugin and create a page for documenting what DashboardClient can do outside of code comments.

**Comment by wwitzel3** [comment]
Where do you see us moving these to? https://reference.octant.dev/?path=/docs/docs-plugins-2-go-plugins--page

**Comment by wwitzel3** [comment]
My thought was that having the "how to" plugin guides and component reference in the same place is useful

**Comment by GuessWhoSamFoo** [comment]
That's fine where it is. I'll add sample code in https://github.com/vmware-tanzu/octant-example-plugins

**Pull request merged**
