### PR TITLE
update electron for osx arm 64

### LINKED ISSUE #1748: Possible problem with new Apple M1 processors
**What steps did you take and what happened:**
Just launch octant, at some random moment in the first minutes, it crashes in a new MacBook Pro (13-inch, M1, 2020) with MacOS Big Sur 11.0.1 (20B29). Terminal iTerm2 launched with Rosetta 2 compatibility (so it should be emulating an Intel processor?).

It doesn't even allow a ctrl+c to kill the process, has to be killed from the Activity Monitor.

```
2020-12-18T14:36:59.355+0100	INFO	dash/dash.go:505	Dashboard is available at http://127.0.0.1:7777

assertion failed [abi_info.kind == AbiKind::TranslatedCode]: emulated forward to an arm pc that isn't in translated code. arm_pc=0x1057844d8 abi_kind=6 emulation_interval=[0x105a2ef80,0x105a2ef94) instruction_interval=[0x105a2ef6c, 0x105a2ef94) x86_rip=0x100fd03
(ThreadContextRegisterState.cpp:677 move_to_instruction_boundary)
```

**What did you expect to happen:**

Not to crash.

**Anything else you would like to add:**

**Environment:**

- Octant version (use `octant version`): 
```
Version:  0.16.3
Git commit:  656c7404e529262861eacb13e88d33dccd6035bf
Built:  2020-12-10T03:48:24Z
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"4fb7ed12476d57b8437ada90b4f93b17ffaeed99", GitTreeState:"clean", BuildDate:"2020-07-15T16:10:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):
```
MacOS Big Sur 11.0.1 (20B29)
```

Strange not to see any other problem here, there are some issues in a lot of open source repositories at the moment (Docker not working, Redis was just fixed...). Somebody can reproduce this?

### PR DESCRIPTION
**Pull request by akhenakh**
**What this PR does / why we need it**:
Because of electon, octant does not build on OSX arm64 (m1)

**Which issue(s) this PR fixes**
- Fixes #1748

**Special notes for your reviewer**:

**Release note**:
```
release-note update electron for osx arm 64
```

### CODE REVIEW

**Comment by GuessWhoSamFoo** [comment]
https://www.electronjs.org/blog/electron-11-0 - that looks right. There's no way to test this via github actions, but we should bump to electron 11 regardless. `package-lock.json` needs to be updated as well

**Comment by GuessWhoSamFoo** [comment]
can you rebase this?

**Comment by akhenakh** [comment]
Since rebase:
```
$ rm -f package-lock.json && npm install --package-lock-only                                                                                                                                                                            
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: dash-frontend@0.0.0
npm ERR! Found: zone.js@0.11.3
npm ERR! node_modules/zone.js
npm ERR!   zone.js@"^0.11.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer zone.js@"~0.10.3" from @angular/core@11.0.8
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"^11.0.7" from the root project
npm ERR!   peer @angular/core@"11.0.8" from @angular/animations@11.0.8
npm ERR!   node_modules/@angular/animations
npm ERR!     @angular/animations@"^11.0.7" from the root project
```

**Comment by GuessWhoSamFoo** [comment]
Not sure what's happening there. My diffs off a8a1bdd look like below and done have any dep conflicts

```
diff --git a/web/package-lock.json b/web/package-lock.json
index 778d0eca..13e72889 100644
--- a/web/package-lock.json
+++ b/web/package-lock.json
@@ -11335,9 +11335,9 @@
       }
     },
     "electron": {
-      "version": "10.2.0",
-      "resolved": "https://registry.npmjs.org/electron/-/electron-10.2.0.tgz",
-      "integrity": "sha512-GBUyq8dwUqXPkCTkoID+eZ5Pm9GFlLUd2eSoGe8UOaHeW68SgCf5t75/uGHraQ1OIz/0qniyH5M4ebWEHGppyQ==",
+      "version": "11.1.1",
+      "resolved": "https://registry.npmjs.org/electron/-/electron-11.1.1.tgz",
+      "integrity": "sha512-tlbex3xosJgfileN6BAQRotevPRXB/wQIq48QeQ08tUJJrXwE72c8smsM/hbHx5eDgnbfJ2G3a60PmRjHU2NhA==",
       "dev": true,
       "requires": {
         "@electron/get": "^1.0.1",
@@ -11346,9 +11346,9 @@
       },
       "dependencies": {
         "@types/node": {
-          "version": "12.19.11",
-          "resolved": "https://registry.npmjs.org/@types/node/-/node-12.19.11.tgz",
-          "integrity": "sha512-bwVfNTFZOrGXyiQ6t4B9sZerMSShWNsGRw8tC5DY1qImUNczS9SjT4G6PnzjCnxsu5Ubj6xjL2lgwddkxtQl5w==",
+          "version": "12.19.13",
+          "resolved": "https://registry.npmjs.org/@types/node/-/node-12.19.13.tgz",
+          "integrity": "sha512-qdixo2f0U7z6m0UJUugTJqVF94GNDkdgQhfBtMs8t5898JE7G/D2kJYw4rc1nzjIPLVAsDkY2MdABnLAP5lM1w==",
           "dev": true
         }
       }
diff --git a/web/package.json b/web/package.json
index 7b4ea1b5..a90ff28f 100644
--- a/web/package.json
+++ b/web/package.json
@@ -102,7 +102,7 @@
     "babel-loader": "^8.1.0",
     "codelyzer": "^6.0.1",
     "dayjs": "^1.9.1",
-    "electron": "^10.1.3",
+    "electron": "^11.1.1",
     "electron-builder": "^22.8.1",
     "jasmine-core": "~3.6.0",
     "jasmine-spec-reporter": "~6.0.0",
(END)
```

**Comment by akhenakh** [comment]
Should be okay now

**Review by GuessWhoSamFoo — APPROVED** [review]
Thanks for the help!

**Pull request merged**
