### PR TITLE
Consolidated preferences storage

### PR DESCRIPTION
**Pull request by mklanjsek**
Added client side preference persistence and hooked up existing preferences to use it.

Details:
- Created general persistence mechanism in preferences service that works in both Electron (using `electron-store`) and browser (using localStorage), 
- Switched save/restore of Electron window bounds to use the new storage,
- Hooked up navigation state and theme to use the same mechanism,
- Removed `astilectron` from client side,
- Removed code that was syncing theme among all opened browser tabs, that would be too intrusive if applied to all preferences,
- Fixed problem with octant tray icon on Mac (#1947),  

Signed-off-by: Milan Klanjsek <mklanjsek@pivotal.io>

### CODE REVIEW

**Review by wwitzel3 — CHANGES_REQUESTED** [review]
This is missing the Frontend Proxy URL setting that was previously in the astielectron code.

**Comment by wwitzel3** [comment]
https://github.com/vmware-tanzu/octant/pull/1955/files#diff-552386b1d1a87b83ec19761da20400e84764c2d6a90c1382723319a99c04722cL137

**Comment by wwitzel3** [comment]
> https://github.com/vmware-tanzu/octant/pull/1955/files#diff-552386b1d1a87b83ec19761da20400e84764c2d6a90c1382723319a99c04722cL137

This is a better link, when it was originally added in #941

**Comment by wwitzel3** [comment]
Slack conversation about this PR https://kubernetes.slack.com/archives/CM37M9FCG/p1612559163090700

**Comment by mklanjsek** [comment]
I think we should merge this now and do Developer level preferences (`frontendUrl` and `logVerbosity`) in separate PR.

**Comment by GuessWhoSamFoo** [comment]
Rebase some of the commit messages please

**Review by GuessWhoSamFoo — APPROVED** [review]

**Pull request merged**
